version: "3.8"

services:
  apisix:
    image: "apache/apisix:${APISIX_DOCKER_TAG:-latest}"
    restart: always
    environment:
      APISIX_STAND_ALONE: "true"
    volumes:
      - ./apisix_conf/master/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/master/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./logs:/usr/local/apisix/logs
    depends_on:
      - etcd
    ports:
      - "9180:9180"
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
    networks: [ apisix ]

  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - ../example/etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379"
    networks: [ apisix ]

  mock-ai-service:
    build:
      context: ./mock-ai-service
    restart: always
    ports:
      - "5001:5001"
    networks: [ apisix ]

  dashboard:
    image: apache/apisix-dashboard:latest
    depends_on:
      - apisix
    volumes:
      - ../example/dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    environment:
      DASHBOARD_API_BASE: http://apisix:9180/apisix
      DASHBOARD_USER: admin
      DASHBOARD_PASSWORD: admin
    ports:
      - "9000:9000"
    networks: [ apisix ]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [ apisix ]

  loki:
    image: grafana/loki:2.8.1
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - ./loki-data:/loki
    ports:
      - "3100:3100"
    networks: [ apisix ]

  grafana:
    image: grafana/grafana:9.5.0
    depends_on:
      - loki
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    networks: [ apisix ]

  fluent-bit:
    image: fluent/fluent-bit:3.0
    depends_on:
      - apisix
      - loki
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./logs:/usr/local/apisix/logs:ro
    command: [ "fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf" ]
    networks: [ apisix ]

networks:
  apisix: {}
