auth_enabled: false

server:
  http_listen_port: 3100
  log_level: debug
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  ingestion_rate_strategy: global
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 168h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compactor_ring:
    kvstore:
      store: inmemory
